training_data = []

training_data.append({"class":"depressed", "sentence":"i am so sad"})
training_data.append({"class":"depressed", "sentence":"i will never be cured"})
training_data.append({"class":"depressed", "sentence":"i am so depressed now"})
training_data.append({"class":"depressed", "sentence":"this is terrible"})
training_data.append({"class":"depressed", "sentence":"want to die"})
training_data.append({"class":"depressed", "sentence":"i feel like killing myself"})
training_data.append({"class":"depressed", "sentence":"i can never be happy in life"})
training_data.append({"class":"depressed", "sentence":"i cant do this anymore"})
training_data.append({"class":"depressed", "sentence":"this is the worst day of my life"})
training_data.append({"class":"depressed", "sentence":"terrible day"})
training_data.append({"class":"depressed", "sentence":"suicide"})
training_data.append({"class":"depressed", "sentence":"death"})
training_data.append({"class":"depressed", "sentence":"im never going to get a bike"})
training_data.append({"class":"depressed", "sentence":"i feel so gloomy today"})
training_data.append({"class":"depressed", "sentence":"i feel so low"})
training_data.append({"class":"depressed", "sentence":"god why does this happen to me"})
training_data.append({"class":"depressed", "sentence":"i feel like shit"})
training_data.append({"class":"depressed", "sentence":"my life sucks"})
training_data.append({"class":"depressed", "sentence":"i hate my life"})
training_data.append({"class":"depressed", "sentence":"i cant believe she did this to me"})
training_data.append({"class":"depressed", "sentence":"i dont think i can recover from this shit"})
training_data.append({"class":"depressed", "sentence":"i will miss her dearly"})
training_data.append({"class":"depressed", "sentence":"i dont think anyone will ever take her place"})
training_data.append({"class":"depressed", "sentence":"i cant take this loss"})
training_data.append({"class":"depressed", "sentence":"ill be dead if this continues"})
training_data.append({"class":"depressed", "sentence":"you're the reason for all this misery"})
training_data.append({"class":"depressed", "sentence":"maybe i dont need to live anymore"})
training_data.append({"class":"depressed", "sentence":"its time i left the world"})
training_data.append({"class":"depressed", "sentence":"im so frustrated"})
training_data.append({"class":"depressed", "sentence":"i cant take this much stress"})
training_data.append({"class":"depressed", "sentence":"i feel so empty"})
training_data.append({"class":"depressed", "sentence":"my life has no meaning"})
training_data.append({"class":"depressed", "sentence":"im clouded with guilt"})
training_data.append({"class":"depressed", "sentence":"I'm lost without love."})
training_data.append({"class":"depressed", "sentence":"I just want to feel like I belong"})
training_data.append({"class":"depressed", "sentence":"My silence is just another word for pain "})
training_data.append({"class":"depressed", "sentence":"Sadness flies away on the wings of time"})
training_data.append({"class":"depressed", "sentence":"Sadness is but a wall between two gardens."})
training_data.append({"class":"depressed", "sentence":"he tragedy of life is not so much what men suffer, but rather what they miss."})
training_data.append({"class":"depressed", "sentence":"The tragedy of life is not that it ends so soon, but that we wait so long to begin it"})
training_data.append({"class":"depressed", "sentence":"I had rather have a fool make me merry, than experience make me sad"})
training_data.append({"class":"depressed", "sentence":"Life isn't fair. It's just fairer than death, that's all."})
training_data.append({"class":"depressed", "sentence":"There is only one rain cloud in the sky...and it's raining on me. Somehow I'm not surprised"})
training_data.append({"class":"depressed", "sentence":"Words hurt more than anything else can, because they last, sometimes forever."})
training_data.append({"class":"depressed", "sentence":"A sad thing in life is that sometimes you meet someone who means a lot to you only to find out in the end that it was never bound to be and you just have to let go"})
training_data.append({"class":"depressed", "sentence":"my life has no meaning"})
training_data.append({"class":"depressed", "sentence":"im clouded with guilt"})
training_data.append({"class":"depressed", "sentence":"Better by far you should forget and smile than that you should remember and be sad."})
training_data.append({"class":"depressed", "sentence":"He is a hard man who is only just, and a sad one who is only wise"})
training_data.append({"class":"depressed", "sentence":"im hurt"})
training_data.append({"class":"depressed", "sentence":"why is this happening to me"})
training_data.append({"class":"depressed", "sentence":"everything bad happens to me"})
training_data.append({"class":"depressed", "sentence":"the world is unfair to me"})
training_data.append({"class":"depressed", "sentence":"im so sad.it will rain on me"})
training_data.append({"class":"depressed", "sentence":"suicide is bliss"})
training_data.append({"class":"depressed", "sentence":"im going to to cry"})
training_data.append({"class":"depressed", "sentence":"i will cry"})
training_data.append({"class":"depressed", "sentence":"i cant stop crying"})
training_data.append({"class":"depressed", "sentence":"i dont want to live life happily"})
training_data.append({"class":"depressed", "sentence":"im a very lonely person"})
training_data.append({"class":"depressed", "sentence":"everyone wants to hurt me"})
training_data.append({"class":"depressed", "sentence":"my life is depressing"})
training_data.append({"class":"depressed", "sentence":"i hate my life"})
training_data.append({"class":"depressed", "sentence":"i hate the face that i have to live"})
training_data.append({"class":"depressed", "sentence":"im depressed"})
training_data.append({"class":"depressed", "sentence":"i want to end my life"})
training_data.append({"class":"depressed", "sentence":"suicide is key"})
training_data.append({"class":"depressed", "sentence":"hurts alot"})
training_data.append({"class":"depressed", "sentence":"hurts to know"})
training_data.append({"class":"depressed", "sentence":"im hurt alot"})
training_data.append({"class":"depressed", "sentence":"i am alone all the time"})
training_data.append({"class":"depressed", "sentence":"i feel lonely"})
training_data.append({"class":"depressed", "sentence":"alone always"})
training_data.append({"class":"depressed", "sentence":"loneliness is my lifetime acheivement"})
training_data.append({"class":"depressed", "sentence":"i dont deserve anything"})
training_data.append({"class":"depressed", "sentence":"i dont deserve this"})
training_data.append({"class":"depressed", "sentence":"i dont deserve anything"})
training_data.append({"class":"depressed", "sentence":"im depressed"})
training_data.append({"class":"depressed", "sentence":"im going into depression"})
training_data.append({"class":"depressed", "sentence":"im failing"})
training_data.append({"class":"depressed", "sentence":"i have failed"})
training_data.append({"class":"depressed", "sentence":"im failing alot"})
training_data.append({"class":"depressed", "sentence":"im a failure"})
training_data.append({"class":"depressed", "sentence":"im disheartened with the results"})
training_data.append({"class":"depressed", "sentence":"i will fail now also"})
training_data.append({"class":"depressed", "sentence":"i failed alone"})
training_data.append({"class":"depressed", "sentence":"alone among people"})
training_data.append({"class":"depressed", "sentence":"im destroyed"})
training_data.append({"class":"depressed", "sentence":"my life is destroyed"})
training_data.append({"class":"depressed", "sentence":"i am dead"})
training_data.append({"class":"depressed", "sentence":"i want to die"})
training_data.append({"class":"depressed", "sentence":"i wanna die"})
training_data.append({"class":"depressed", "sentence":"death is nearing me"})
training_data.append({"class":"depressed", "sentence":"im going to hell"})
training_data.append({"class":"depressed", "sentence":"i hate my life"})
training_data.append({"class":"depressed", "sentence":"i am so unhappy"})
training_data.append({"class":"depressed", "sentence":"i am not happy at all"})
training_data.append({"class":"depressed", "sentence":"i am saaaaaaaaaaaaaaaaad"})





training_data.append({"class":"happy", "sentence":"this is the best day ever"})
training_data.append({"class":"happy", "sentence":"yay"})
training_data.append({"class":"happy", "sentence":"i am going to party today"})
training_data.append({"class":"happy", "sentence":"i love alcohol, beer and vodka"})
training_data.append({"class":"happy", "sentence":"wow"})
training_data.append({"class":"happy", "sentence":"i like smoking up"})
training_data.append({"class":"happy", "sentence":"i like beer"})
training_data.append({"class":"happy", "sentence":"i love ice-cream"})
training_data.append({"class":"happy", "sentence":"ice-cream is amazing"})
training_data.append({"class":"happy", "sentence":"im so ecstatic"})
training_data.append({"class":"happy", "sentence":"this is the best day of my life"})
training_data.append({"class":"happy", "sentence":"i am so happy"})
training_data.append({"class":"happy", "sentence":"i feel like flying"})
training_data.append({"class":"happy", "sentence":"im the best"})
training_data.append({"class":"happy", "sentence":"im on top of the world"})
training_data.append({"class":"happy", "sentence":"she's the best thing that EVER happened to me"})
training_data.append({"class":"happy", "sentence":"im on cloud nine"})
training_data.append({"class":"happy", "sentence":"im going to have a baby"})
training_data.append({"class":"happy", "sentence":"this is amazing"})
training_data.append({"class":"happy", "sentence":"beautiful weather"})
training_data.append({"class":"happy", "sentence":"omg wow"})
training_data.append({"class":"happy", "sentence":"this is euphoric"})
training_data.append({"class":"happy", "sentence":"i am terribly happy"})
training_data.append({"class":"happy", "sentence":"i am happily married"})
training_data.append({"class":"happy", "sentence":"i love watching porn"})
training_data.append({"class":"happy", "sentence":"this chicken tastes so good"})
training_data.append({"class":"happy", "sentence":"satisfied"})
training_data.append({"class":"happy", "sentence":"i am fond of chips"})
training_data.append({"class":"happy", "sentence":"i adore her beauty"})
training_data.append({"class":"happy", "sentence":"i admire his innocence"})
training_data.append({"class":"happy", "sentence":"i love you"})
training_data.append({"class":"happy", "sentence":"love is a beautiful thing"})
training_data.append({"class":"happy", "sentence":"love at its best"})
training_data.append({"class":"happy", "sentence":"im on cloud 9 today"})
training_data.append({"class":"happy", "sentence":"i am never sad"})
training_data.append({"class":"happy", "sentence":"this is the best day of my life"})
training_data.append({"class":"happy", "sentence":"best day ever"})
training_data.append({"class":"happy", "sentence":"laughing is key"})
training_data.append({"class":"happy", "sentence":"laughd alot today"})
training_data.append({"class":"happy", "sentence":"love has this warmth"})
training_data.append({"class":"happy", "sentence":"this is love"})
training_data.append({"class":"happy", "sentence":"not sad today"})
training_data.append({"class":"happy", "sentence":"not sad"})
training_data.append({"class":"happy", "sentence":"im not disheartened"})
training_data.append({"class":"happy", "sentence":"life at its best"})
training_data.append({"class":"happy", "sentence":"life is beautiful"})
training_data.append({"class":"happy", "sentence":"wow this is amazing"})
training_data.append({"class":"happy", "sentence":"life has never been this good"})
training_data.append({"class":"happy", "sentence":"this is beautiful"})
training_data.append({"class":"happy", "sentence":"yayy!!!!"})
training_data.append({"class":"happy", "sentence":"not sad"})
training_data.append({"class":"happy", "sentence":"not a bad day"})
training_data.append({"class":"happy", "sentence":"not horrible today"})
training_data.append({"class":"happy", "sentence":"not a bad time"})
training_data.append({"class":"happy", "sentence":"not a bad saying"})
training_data.append({"class":"happy", "sentence":"the best time since forever"})
training_data.append({"class":"happy", "sentence":"my team won the match today"})
training_data.append({"class":"happy", "sentence":"i love royal challengers bangalore"})
training_data.append({"class":"happy", "sentence":"im going on a holiday"})
training_data.append({"class":"happy", "sentence":"i love to watch him play"})
training_data.append({"class":"happy", "sentence":"i love playing football"})
training_data.append({"class":"happy", "sentence":"i love it when cops chase me"})

training_data.append({"class":"angry", "sentence":"get lost"})
training_data.append({"class":"angry", "sentence":" wtf"})
training_data.append({"class":"angry", "sentence":"i hate him"})
training_data.append({"class":"angry", "sentence":"hes the most disgusting person ever"})
training_data.append({"class":"angry", "sentence":" gross"})
training_data.append({"class":"angry", "sentence":"stop pissing me off"})
training_data.append({"class":"angry", "sentence":" pathetic you are"})
training_data.append({"class":"angry", "sentence":"get lost maniac"})
training_data.append({"class":"angry", "sentence":"you suck"})
training_data.append({"class":"angry", "sentence":"i am so angry at you"})
training_data.append({"class":"angry", "sentence":"dont bother me"})
training_data.append({"class":"angry", "sentence":"go away piece of shit"})
training_data.append({"class":"angry", "sentence":"leave me alone"})
training_data.append({"class":"angry", "sentence":"go away forever"})
training_data.append({"class":"angry", "sentence":"you are the worst"})
training_data.append({"class":"angry", "sentence":"worst time ever"})
training_data.append({"class":"angry", "sentence":" this is not good at all"})
training_data.append({"class":"angry", "sentence":"dont you dare"})
training_data.append({"class":"angry", "sentence":"i dare you"})
training_data.append({"class":"angry", "sentence":"too much attitude"})
training_data.append({"class":"angry", "sentence":"annoying as hell"})
training_data.append({"class":"angry", "sentence":"to hell with you"})
training_data.append({"class":"angry", "sentence":"get away"})
training_data.append({"class":"angry", "sentence":"lavanya talks too much"})
training_data.append({"class":"angry", "sentence":"thunne unnu"})
training_data.append({"class":"angry", "sentence":"saale madarchod"})
training_data.append({"class":"angry", "sentence":"teri maa ki saaki naaka"})
training_data.append({"class":"angry", "sentence":"see, i dont give a fuck"})
training_data.append({"class":"angry", "sentence":"stop acting like a dickhead"})
training_data.append({"class":"angry", "sentence":"fml"})
training_data.append({"class":"angry", "sentence":"can you please stop acting like an asshole"})
training_data.append({"class":"angry", "sentence":"stop harrassing me"})
training_data.append({"class":"angry", "sentence":"stop eating my lunch all the time"})
training_data.append({"class":"angry", "sentence":"stop fucking that bitch, come lay with me"})
training_data.append({"class":"angry", "sentence":"she's not listening to me"})
training_data.append({"class":"angry", "sentence":"he drives like a piece of shit"})
training_data.append({"class":"angry", "sentence":"imma kill you"})
training_data.append({"class":"angry", "sentence":"you stupid ass hoe"})
training_data.append({"class":"angry", "sentence":"im going to cut your dick off"})
training_data.append({"class":"angry", "sentence":"imma rip your balls out"})
training_data.append({"class":"angry", "sentence":"vengeance will be served"})
training_data.append({"class":"angry", "sentence":"i will have my revenge"})
training_data.append({"class":"angry", "sentence":"fuck my life"})
training_data.append({"class":"angry", "sentence":"im not a bitch like you "})
training_data.append({"class":"angry", "sentence":"fuck off bitch don't piss me off"})




training_data.append({"class":"scared", "sentence":"please dont do this to me"})
training_data.append({"class":"scared", "sentence":"im really scared now"})
training_data.append({"class":"scared", "sentence":"this is frightening"})
training_data.append({"class":"scared", "sentence":"im haunted"})
training_data.append({"class":"scared", "sentence":"this is such a nightmare"})
training_data.append({"class":"scared", "sentence":"im too scared to do this"})
training_data.append({"class":"scared", "sentence":"he's bullying me and i can't take it anymore"})
training_data.append({"class":"scared", "sentence":"im getting bullied at school"})
training_data.append({"class":"scared", "sentence":"i live in constant fear of him"})
training_data.append({"class":"scared", "sentence":"i cant get out of the house because he may kill me"})
training_data.append({"class":"scared", "sentence":"i think hes gonna kill me"})
training_data.append({"class":"scared", "sentence":"im scared that she may do something"})
training_data.append({"class":"scared", "sentence":"i dont want him to kill himself"})
training_data.append({"class":"scared", "sentence":"im scared of the dark"})
training_data.append({"class":"scared", "sentence":"im scared that the dog will bite me"})
training_data.append({"class":"scared", "sentence":"im scared ill die a virgin"})
training_data.append({"class":"scared", "sentence":"im scared ill get rejected"})
training_data.append({"class":"scared", "sentence":"i fear death"})
training_data.append({"class":"scared", "sentence":"okay this is not funny"})
training_data.append({"class":"scared", "sentence":"i hope i dont get murdered"})
training_data.append({"class":"scared", "sentence":"i hope that lady doesnt kill me"})
training_data.append({"class":"scared", "sentence":"im scared ill die crossing the road"})
training_data.append({"class":"scared", "sentence":"im scared of going fast"})
training_data.append({"class":"scared", "sentence":"im scared ill give in to temptation and do drugs"})
training_data.append({"class":"scared", "sentence":"im really scared of him"})



training_data.append({"class":"sad", "sentence":"my team lost the finals"})
training_data.append({"class":"sad", "sentence":"i am so unhappy"})
training_data.append({"class":"sad", "sentence":"india lost the match today"})
training_data.append({"class":"sad", "sentence":"prajwal has to sit next to lavanya everyday"})
training_data.append({"class":"sad", "sentence":"the results were diheartening"})
training_data.append({"class":"sad", "sentence":"i think i should stop dancing"})
training_data.append({"class":"sad", "sentence":"i wont be able to come to play today :("})
training_data.append({"class":"sad", "sentence":"i cant go for a holiday"})
training_data.append({"class":"sad", "sentence":"my car broke down"})
training_data.append({"class":"sad", "sentence":"i cant walk properly"})
training_data.append({"class":"sad", "sentence":"i may not be able to see for the rest of my life"})
training_data.append({"class":"sad", "sentence":"i haven't seen my friend in ages"})
training_data.append({"class":"sad", "sentence":"shes annoyed with me"})
training_data.append({"class":"sad", "sentence":"my pizza fell down on the floor"})
training_data.append({"class":"sad", "sentence":"the dog ate my car keys"})
training_data.append({"class":"sad", "sentence":"i lost the match"})
training_data.append({"class":"sad", "sentence":"i cant attend the concert"})
training_data.append({"class":"sad", "sentence":"i cant play anymore"})
training_data.append({"class":"sad", "sentence":"my team sucks"})
training_data.append({"class":"sad", "sentence":"i feel sad"})
training_data.append({"class":"sad", "sentence":"im so sad"})
training_data.append({"class":"sad", "sentence":"she should've won"})
training_data.append({"class":"sad", "sentence":"i shouldve done better in my exams"})
training_data.append({"class":"sad", "sentence":"my holidays are getting over"})
training_data.append({"class":"sad", "sentence":"i havent watched a movie in ages"})
training_data.append({"class":"sad", "sentence":"i havent eaten pizza this week"})
training_data.append({"class":"sad", "sentence":"i have to sacrifice for the greater good"})
training_data.append({"class":"sad", "sentence":"im gonna have to stop playing clash royale"})

training_data.append({"class":"neutral", "sentence":"i am not unhappy"})
training_data.append({"class":"neutral", "sentence":"i am not disheartened"})
training_data.append({"class":"neutral", "sentence":"i am not irresponsible"})
training_data.append({"class":"neutral", "sentence":"i cant not care"})
training_data.append({"class":"neutral", "sentence":"she looks really pretty"})
training_data.append({"class":"neutral", "sentence":"i dont support anyone or anything"})
training_data.append({"class":"neutral", "sentence":"the heat is not unbearable"})
training_data.append({"class":"neutral", "sentence":"this song is decent"})
training_data.append({"class":"neutral", "sentence":"this is a neutral sentence"})
training_data.append({"class":"neutral", "sentence":"the beach is filled with sand"})
training_data.append({"class":"neutral", "sentence":"she looks like my mom"})
training_data.append({"class":"neutral", "sentence":"the beach is really blue today"})
training_data.append({"class":"neutral", "sentence":"he's talking to someone"})
training_data.append({"class":"neutral", "sentence":"im doing an internship for the summer"})
training_data.append({"class":"neutral", "sentence":"i have too many clothes"})
training_data.append({"class":"neutral", "sentence":"its sunny today"})
training_data.append({"class":"neutral", "sentence":"the sun rises in the east"})
training_data.append({"class":"neutral", "sentence":"i have curly hair"})
training_data.append({"class":"neutral", "sentence":"the banks are closed today"})
training_data.append({"class":"neutral", "sentence":"i have a black bag"})
training_data.append({"class":"neutral", "sentence":"there is a cricket match in my city today"})
training_data.append({"class":"neutral", "sentence":"they sit next to each other"})
training_data.append({"class":"neutral", "sentence":"my keyboard has a white backlight"})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})
training_data.append({"class":"neutral", "sentence":""})




